[system]
#每8秒执行一次
job_entering_house_sleep = 8
#每日4点
job_truncate_hour = 4
#每日1点
job_analysis_hour = 1
#每1小时刷新实时
job_analysis_refresh_hour = 1
#批量插入最大条数
job_entering_house_max_count = 1000

qiniu_bucket = ""
qiniu_access_key = ""
qiniu_secret_key = ""
qiniu_expire = 1200
qiniu_domain = "http://www"

[other]
listen_addr = ":8000"
service_name = "cdp-service"
repository_request_timeout = 10
prometheus_listen_addr = ":9090"
# "fatal" "error" "warn" "info"  "debug"
logger_level = "debug"
logger_path = "./log"
logger_console = true
# shutdown_second : Elegant lying off for the longest time
shutdown_second = 3

