//Package domain generated by 'freedom new-project cdp-service'
package domain

import (
	"cdp-service/adapter/repository"

	"github.com/8treenet/freedom"
)

func init() {
	freedom.Prepare(func(initiator freedom.Initiator) {
		initiator.BindService(func() *DefaultSvr {
			return &DefaultSvr{}
		})
		initiator.InjectController(func(ctx freedom.Context) (service *DefaultSvr) {
			initiator.FetchService(ctx, &service)
			return
		})
	})
}

// DefaultSvr .
type DefaultSvr struct {
	Worker  freedom.Worker
	DefRepo *repository.DefaultRepo
}

// RemoteInfo .
func (svr *DefaultSvr) RemoteInfo() (result struct {
	Ip string
	Ua string
}) {
	svr.Worker.Logger().Info("I'm service")
	result.Ip = svr.DefRepo.GetIP()
	result.Ua = svr.DefRepo.GetUA()
	return
}

// GetCommon .
func (svr *DefaultSvr) GetCommon() string {
	//service 调用repository
	return svr.DefRepo.GetCommon()
}
