//Package po generated by 'freedom new-po'
package po

import (
	"gorm.io/gorm"
	"time"
)

// Persona .
type Persona struct {
	changes   map[string]interface{}
	ID        int       `gorm:"primaryKey;column:id"`
	Name      string    `gorm:"column:name"`      // 名称
	Title     string    `gorm:"column:title"`     // 显示名称
	DateRange int       `gorm:"column:dateRange"` // 天/范围
	XMLData   string    `gorm:"column:xmlData"`   // xml条件数据
	Created   time.Time `gorm:"column:created"`
	Updated   time.Time `gorm:"column:updated"`
	Deleted   int       `gorm:"column:deleted"`
}

// TableName .
func (obj *Persona) TableName() string {
	return "cdp_persona"
}

// Location .
func (obj *Persona) Location() map[string]interface{} {
	return map[string]interface{}{"id": obj.ID}
}

// GetChanges .
func (obj *Persona) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *Persona) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetName .
func (obj *Persona) SetName(name string) {
	obj.Name = name
	obj.Update("name", name)
}

// SetTitle .
func (obj *Persona) SetTitle(title string) {
	obj.Title = title
	obj.Update("title", title)
}

// SetDateRange .
func (obj *Persona) SetDateRange(dateRange int) {
	obj.DateRange = dateRange
	obj.Update("dateRange", dateRange)
}

// SetXMLData .
func (obj *Persona) SetXMLData(xMLData string) {
	obj.XMLData = xMLData
	obj.Update("xmlData", xMLData)
}

// SetCreated .
func (obj *Persona) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *Persona) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}

// SetDeleted .
func (obj *Persona) SetDeleted(deleted int) {
	obj.Deleted = deleted
	obj.Update("deleted", deleted)
}

// AddDateRange .
func (obj *Persona) AddDateRange(dateRange int) {
	obj.DateRange += dateRange
	obj.Update("dateRange", gorm.Expr("dateRange + ?", dateRange))
}

// AddDeleted .
func (obj *Persona) AddDeleted(deleted int) {
	obj.Deleted += deleted
	obj.Update("deleted", gorm.Expr("deleted + ?", deleted))
}
