//Package po generated by 'freedom new-po'
package po

import (
	"time"
)

// Customer .
type Customer struct {
	changes       map[string]interface{}
	UserID        string    `gorm:"primaryKey;column:userId" json:"userID"`
	Name          string    `gorm:"column:name" json:"name"`                   // 名称
	Email         string    `gorm:"column:email" json:"email"`                 // 邮箱
	Phone         string    `gorm:"column:phone" json:"phone"`                 // 电话
	Gender        string    `gorm:"column:gender" json:"gender"`               // 性别
	Birthday      string    `gorm:"column:birthday" json:"birthday"`           // 生日
	Province      string    `gorm:"column:province" json:"province"`           // 省
	City          string    `gorm:"column:city" json:"city"`                   // 市
	Region        string    `gorm:"column:region" json:"region"`               // 区
	WechatUnionID string    `gorm:"column:wechatUnionId" json:"wechatUnionID"` // 微信唯一id
	Key           string    `gorm:"column:key" json:"key"`                     // 自定义识别key
	Created       time.Time `gorm:"column:created" json:"created"`
	Updated       time.Time `gorm:"column:updated" json:"updated"`
}

// TableName .
func (obj *Customer) TableName() string {
	return "cdp_customer"
}

// Location .
func (obj *Customer) Location() map[string]interface{} {
	return map[string]interface{}{"userId": obj.UserID}
}

// GetChanges .
func (obj *Customer) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *Customer) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetName .
func (obj *Customer) SetName(name string) {
	obj.Name = name
	obj.Update("name", name)
}

// SetEmail .
func (obj *Customer) SetEmail(email string) {
	obj.Email = email
	obj.Update("email", email)
}

// SetPhone .
func (obj *Customer) SetPhone(phone string) {
	obj.Phone = phone
	obj.Update("phone", phone)
}

// SetGender .
func (obj *Customer) SetGender(gender string) {
	obj.Gender = gender
	obj.Update("gender", gender)
}

// SetBirthday .
func (obj *Customer) SetBirthday(birthday string) {
	obj.Birthday = birthday
	obj.Update("birthday", birthday)
}

// SetProvince .
func (obj *Customer) SetProvince(province string) {
	obj.Province = province
	obj.Update("province", province)
}

// SetCity .
func (obj *Customer) SetCity(city string) {
	obj.City = city
	obj.Update("city", city)
}

// SetRegion .
func (obj *Customer) SetRegion(region string) {
	obj.Region = region
	obj.Update("region", region)
}

// SetWechatUnionID .
func (obj *Customer) SetWechatUnionID(wechatUnionID string) {
	obj.WechatUnionID = wechatUnionID
	obj.Update("wechatUnionId", wechatUnionID)
}

// SetKey .
func (obj *Customer) SetKey(key string) {
	obj.Key = key
	obj.Update("key", key)
}

// SetCreated .
func (obj *Customer) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *Customer) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}
