//Package po generated by 'freedom new-po'
package po

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// CustomerExtend .
type CustomerExtend struct {
	changes map[string]interface{}
	ID      int            `gorm:"primaryKey;column:id"`
	UserID  int            `gorm:"column:userId"`
	Data    datatypes.JSON `gorm:"column:data"` // 扩展数据
	Created time.Time      `gorm:"column:created"`
	Updated time.Time      `gorm:"column:updated"`
}

// TableName .
func (obj *CustomerExtend) TableName() string {
	return "cdp_customer_extend"
}

// Location .
func (obj *CustomerExtend) Location() map[string]interface{} {
	return map[string]interface{}{"id": obj.ID}
}

// GetChanges .
func (obj *CustomerExtend) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *CustomerExtend) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetUserID .
func (obj *CustomerExtend) SetUserID(userID int) {
	obj.UserID = userID
	obj.Update("userId", userID)
}

// SetData .
func (obj *CustomerExtend) SetData(data datatypes.JSON) {
	obj.Data = data
	obj.Update("data", data)
}

// SetCreated .
func (obj *CustomerExtend) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *CustomerExtend) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}

// AddUserID .
func (obj *CustomerExtend) AddUserID(userID int) {
	obj.UserID += userID
	obj.Update("userId", gorm.Expr("userId + ?", userID))
}
