//Package po generated by 'freedom new-po'
package po

import (
	"time"
)

// BehaviourSource .
type BehaviourSource struct {
	changes map[string]interface{}
	ID      int       `gorm:"primaryKey;column:id"`
	Source  string    `gorm:"column:source"`
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
}

// TableName .
func (obj *BehaviourSource) TableName() string {
	return "cdp_behaviour_source"
}

// Location .
func (obj *BehaviourSource) Location() map[string]interface{} {
	return map[string]interface{}{"id": obj.ID}
}

// GetChanges .
func (obj *BehaviourSource) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *BehaviourSource) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetSource .
func (obj *BehaviourSource) SetSource(source string) {
	obj.Source = source
	obj.Update("source", source)
}

// SetCreated .
func (obj *BehaviourSource) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *BehaviourSource) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}
