//Package po generated by 'freedom new-po'
package po

import (
	"time"
)

// CustomerKey .
type CustomerKey struct {
	changes map[string]interface{}
	ID      int       `gorm:"primaryKey;column:id"`
	UserID  string    `gorm:"column:userId"`  // 用户userid
	UserKey string    `gorm:"column:userKey"` // 唯一key
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
}

// TableName .
func (obj *CustomerKey) TableName() string {
	return "cdp_customer_key"
}

// Location .
func (obj *CustomerKey) Location() map[string]interface{} {
	return map[string]interface{}{"id": obj.ID}
}

// GetChanges .
func (obj *CustomerKey) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *CustomerKey) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetUserID .
func (obj *CustomerKey) SetUserID(userID string) {
	obj.UserID = userID
	obj.Update("userId", userID)
}

// SetUserKey .
func (obj *CustomerKey) SetUserKey(userKey string) {
	obj.UserKey = userKey
	obj.Update("userKey", userKey)
}

// SetCreated .
func (obj *CustomerKey) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *CustomerKey) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}
