//Package po generated by 'freedom new-po'
package po

import (
	"gorm.io/gorm"
	"time"
)

// CustomerPhone .
type CustomerPhone struct {
	changes map[string]interface{}
	ID      int       `gorm:"primaryKey;column:id"`
	UserID  int       `gorm:"column:userId"` // 用户userid
	Phone   string    `gorm:"column:phone"`  // 手机号
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
}

// TableName .
func (obj *CustomerPhone) TableName() string {
	return "cdp_customer_phone"
}

// Location .
func (obj *CustomerPhone) Location() map[string]interface{} {
	return map[string]interface{}{"id": obj.ID}
}

// GetChanges .
func (obj *CustomerPhone) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *CustomerPhone) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetUserID .
func (obj *CustomerPhone) SetUserID(userID int) {
	obj.UserID = userID
	obj.Update("userId", userID)
}

// SetPhone .
func (obj *CustomerPhone) SetPhone(phone string) {
	obj.Phone = phone
	obj.Update("phone", phone)
}

// SetCreated .
func (obj *CustomerPhone) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *CustomerPhone) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}

// AddUserID .
func (obj *CustomerPhone) AddUserID(userID int) {
	obj.UserID += userID
	obj.Update("userId", gorm.Expr("userId + ?", userID))
}
