//Package po generated by 'freedom new-po'
package po

import (
	"gorm.io/gorm"
	"time"
)

// CustomerWechat .
type CustomerWechat struct {
	changes map[string]interface{}
	ID      int       `gorm:"primaryKey;column:id"`
	UserID  int       `gorm:"column:userId"`  // 用户userid
	UnionID string    `gorm:"column:unionId"` // 唯一id
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
}

// TableName .
func (obj *CustomerWechat) TableName() string {
	return "cdp_customer_wechat"
}

// Location .
func (obj *CustomerWechat) Location() map[string]interface{} {
	return map[string]interface{}{"id": obj.ID}
}

// GetChanges .
func (obj *CustomerWechat) GetChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// Update .
func (obj *CustomerWechat) Update(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetUserID .
func (obj *CustomerWechat) SetUserID(userID int) {
	obj.UserID = userID
	obj.Update("userId", userID)
}

// SetUnionID .
func (obj *CustomerWechat) SetUnionID(unionID string) {
	obj.UnionID = unionID
	obj.Update("unionId", unionID)
}

// SetCreated .
func (obj *CustomerWechat) SetCreated(created time.Time) {
	obj.Created = created
	obj.Update("created", created)
}

// SetUpdated .
func (obj *CustomerWechat) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.Update("updated", updated)
}

// AddUserID .
func (obj *CustomerWechat) AddUserID(userID int) {
	obj.UserID += userID
	obj.Update("userId", gorm.Expr("userId + ?", userID))
}
