//Package vo generated by 'freedom new-project github.com/8treenet/cdp-service'
//Value Object in domain-driven design
package vo

import (
	"github.com/8treenet/cdp-service/domain/po"
)

type CustomerDTO struct {
	po.Customer
	Extension          map[string]interface{} `json:"extension"`
	BirthdaySubstitute string                 `json:"birthday"`
	Source             string                 `json:"source"`
}
