//Package vo generated by 'freedom new-project github.com/8treenet/cdp-service'
//Value Object in domain-driven design
package vo

import (
	"github.com/8treenet/cdp-service/domain/po"
)

type CustomerDTO struct {
	po.Customer
	Extension          map[string]interface{} `json:"extension"`
	BirthdaySubstitute string                 `json:"birthday"`
	Source             string                 `json:"source"`
	IP                 string                 `json:"ip"`
}

type PostFeatureMetadataDTO struct {
	Variable string `json:"variable"` // 类型的名称
	Title    string `json:"title"`    // 中文的标题
	Kind     string `json:"kind"`     // 类型
	Dict     string `json:"dict"`     // 关联字典的key
}

type PostFeatureDTO struct {
	Title     string                   `json:"title"`
	Warehouse string                   `json:"warehouse"` // clickhouse的表名
	Metadata  []PostFeatureMetadataDTO `json:"metadata"`
}
