//Package vo generated by 'freedom new-project github.com/8treenet/crm-service'
//Value Object in domain-driven design
package vo

import (
	"time"

	"github.com/8treenet/crm-service/domain/po"
)

func NewCustomerTemplateFromPO(po *po.CustomerTemplate) *CustomerTemplate {
	return &CustomerTemplate{
		ID:       po.ID,
		Name:     po.Name,
		Kind:     po.Kind,
		Index:    po.Index,
		Dict:     po.Dict,
		Reg:      po.Reg,
		Required: po.Required,
		Sort:     po.Sort,
		Created:  po.Created,
		Updated:  po.Updated,
	}
}

// CustomerTemplate .
type CustomerTemplate struct {
	ID       int       `json:"id"`
	Name     string    `json:"name" validate:"required"`
	Kind     string    `json:"kind" validate:"required"`
	Index    int       `json:"index"`
	Dict     string    `json:"dict"`
	Reg      string    `json:"reg"`
	Required int       `json:"required"`
	Sort     int       `json:"sort"`
	Created  time.Time `json:"created"`
	Updated  time.Time `json:"updated"`
}
